#!/bin/bash

# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2019, Technologic Systems Inc.

interface=$(echo $1 | cut -d '.' -f1)
increment=$(echo $1 | cut -d '.' -f2)

let "increment=$increment-1"
eval `/usr/local/bin/getmac ${interface}`
mac2=$(printf "%x\n" $(echo $((0x$shortmac+$increment))) | sed "s/.*\(..\)\(..\)\(..\)/00:d0:69:\1:\2:\3/")

echo $mac2

