#!/bin/bash

# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2019-2022 Technologic Systems, Inc. dba embeddedTS

# Due to observed issues in some power installations, the script below has the
# following behavior:
#   - Once every half second, read the POWER_FAIL bit
#   - If POWER_FAIL, monitor pct through tsmicroctl once per half second.
#   - If pct is less than the threshold -AND- POWER_FAIL has been asserted for
#       at least two checks in a row, then reboot the system.
# The above AND is necessary to not reboot on spurious power fail events

# Conservative value to wait for until shutting down
RESET_PCT=90

echo 73 > /sys/class/gpio/export 2>/dev/null

while true; do
    power=$(cat /sys/class/gpio/gpio73/value)
    if [ "${power}" -ne 0 ]; then

        # Not all tsmicroctl builds support reporting the supercap charge level.
        # In the case of this string not being set, then just assume the current
        # level is 0 and spit information out to the logs.
        eval "$(tsmicroctl -i)"
        if [ ! -z "${supercap_pct}" ]; then
            echo "Supercapacitors at ${supercap_pct}"
        else
            echo "\'tsmicroctl\' does not support reading charge percentage!"
            echo "Please update \'tsmicroctl\'!"
            supercap_pct=0
        fi

        if [ "${supercap_pct}" -le $RESET_PCT ]; then
            if [ "${power_failed}" -gt 0 ]; then
                # Code can be added below in order to turn off power-hungry
                # devices, or start other shutdown procedures required.
                # For example:
                # Turn off cell modem on DC:
                #   echo 233 > /sys/class/gpio/export 2>/dev/null
                #   echo low > /sys/class/gpio/gpio233/direction
                #
                # Disable relays
                #   echo 210 > /sys/class/gpio/export 2>/dev/null
                #   echo 211 > /sys/class/gpio/export 2>/dev/null
                #   echo low > /sys/class/gpio/gpio210/direction
                #   echo low > /sys/class/gpio/gpio211/direction
                #
                # The wall command can be removed if wanted.

                wall The script /usr/local/bin/tssupercapmon has detected main power has been lost!  Shutting down safely to prevent filesystem damage

		reboot
                exit
            fi
        fi
        let power_failed=power_failed+1
    else
        power_failed=0
    fi

    sleep .5
done
 
