#!/bin/bash

# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2019, Technologic Systems Inc.

# Note! This script is only needed in the 3.14 Debian Jessie images
# It is not advised to run this script on the 4.9 Debian Stretch image

#Enable CAN
echo 126 > /sys/class/gpio/export
echo low > /sys/class/gpio/gpio126/direction

#Generate new host keys, if old ones are deleted
test -f /etc/ssh/ssh_host_dsa_key || dpkg-reconfigure openssh-server

#Turn off red LED
echo 7 > /sys/class/gpio/export
echo high > /sys/class/gpio/gpio7/direction

